# Generated by Django 5.0.7 on 2024-08-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("map", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="media",
            options={"verbose_name": "Media", "verbose_name_plural": "Medias"},
        ),
    ]
